export enum InvalidUsernameReason {
    TOO_SHORT = "TOO_SHORT",
    TOO_LONG = "TOO_LONG",
    INVALID_CHARACTERS = "INVALID_CHARACTERS",
    ALREADY_EXISTS = "ALREADY_EXISTS",
    VIOLATES_COMMUNITY_GUIDELINES = "VIOLATES_COMMUNITY_GUIDELINES",
}